/** @type {import('prettier').Config} */
module.exports = {
  tailwindFunctions: ['clsx'],
  endOfLine: "lf",
  semi: false,
  singleQuote: false,
  tabWidth: 2,
  trailingComma: "es5",
  importOrder: [
    "^(react/(.*)$)|^(react$)",
    "^(next/(.*)$)|^(next$)",
    "<THIRD_PARTY_MODULES>",
    "",
    "^types$",
    "^@/types/(.*)$",
    "^@/config/(.*)$",
    "^@/lib/(.*)$",
    "^@/hooks/(.*)$",
    "^@/components/about/(.*)$",
    "^@/components/blog/(.*)$",
    "^@/components/brands/(.*)$",
    "^@/components/common/(.*)$",
    "^@/components/contact/(.*)$",
    "^@/components/features/(.*)$",
    "^@/components/footer/(.*)$",
    "^@/components/header/(.*)$",
    "^@/components/hero/(.*)$",
    "^@/components/practice/(.*)$",
    "^@/components/pricing/(.*)$",
    "^@/components/scroll-to-top/(.*)$",
    "^@/components/testimonials/(.*)$",
    "^@/components/video/(.*)$",
    "^@/components/ui/(.*)$",
    "^@/components/(.*)$",
    "^@/styles/(.*)$",
    "^@/app/(.*)$",
    "",
    "^[./]",
  ],
  // Migrating from v3.x.x to v4.x.x
  // importOrderSeparation: false,
  // importOrderMergeDuplicateImports: true,
  // importOrderCombineTypeAndValueImports: true,
  // importOrderBuiltinModulesToTop: true,
  // importOrderSortSpecifiers: true,
  importOrderParserPlugins: ["typescript", "jsx", "decorators-legacy"],
  importOrderTypeScriptVersion: '5.0.0',
  plugins: ["prettier-plugin-tailwindcss", "@ianvs/prettier-plugin-sort-imports"],
}